### PR TITLE
handle loss of exif by rotating image

### PR DESCRIPTION
**Pull request by JamesHannon**
EXIF data is getting lost during image processing (I'm coming to this from django-thumbnails), this change strips out the exif data and rotates the image to compensate

### CODE REVIEW

**Review by MikeyZat — APPROVED** [review]

**Comment by MikeyZat** [comment]
@selwin @SeiryuZ could we review & merge it? The exif metadata issues is very painful in our project and we'd like to continue using `da-vinci`

**Comment by selwin** [comment]
Will look at this soon

**Comment by selwin** [comment]
Thanks!

**Comment by MikeyZat** [comment]
thank you so much, looking forward to the next release :)

**Comment by selwin** [comment]
Should be sometime this week :)

**Comment by selwin** [comment]
Version 0.4.0 is now released @MikeyZat

**Pull request merged**
